### ISSUE TITLE
Is the code able to decode all IEC104 messages?

### ISSUE THREAD

**Issue by jimbung** [ortecs/IEC104#1]

**Comment by tritaer** [comment]
Hi, for now support next type of ASDU types  '01', '02', '03', '04', '05', '06', '07', '08', '09', '0A', '0B', '0C', '0D', '0E', '15', '1E', '1F', '20', '21', '22', '23', '24', '26', '27'
If you can provide example of other type msg, i can add support to them

**Comment by jimbung** [comment]
OK. I'll investigate & report later. Thank you very much!
